FROM golang:1.24.3

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ./bin/main ./cmd/app

ENTRYPOINT ["/go/bin/air"]
